//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWS.ServiceClienteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceClienteWS.wsoperaciones")]
    public interface wsoperaciones {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/wsoperaciones/helloRequest", ReplyAction="http://ws/wsoperaciones/helloResponse")]
        ClienteWS.ServiceClienteWS.helloResponse hello(ClienteWS.ServiceClienteWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/wsoperaciones/helloRequest", ReplyAction="http://ws/wsoperaciones/helloResponse")]
        System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.helloResponse> helloAsync(ClienteWS.ServiceClienteWS.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/wsoperaciones/ProcesarPagoRequest", ReplyAction="http://ws/wsoperaciones/ProcesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteWS.ServiceClienteWS.ProcesarPagoResponse ProcesarPago(ClienteWS.ServiceClienteWS.ProcesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/wsoperaciones/ProcesarPagoRequest", ReplyAction="http://ws/wsoperaciones/ProcesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.ProcesarPagoResponse> ProcesarPagoAsync(ClienteWS.ServiceClienteWS.ProcesarPagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/wsoperaciones/LogginRequest", ReplyAction="http://ws/wsoperaciones/LogginResponse")]
        ClienteWS.ServiceClienteWS.LogginResponse Loggin(ClienteWS.ServiceClienteWS.LogginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/wsoperaciones/LogginRequest", ReplyAction="http://ws/wsoperaciones/LogginResponse")]
        System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.LogginResponse> LogginAsync(ClienteWS.ServiceClienteWS.LogginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://ws/", Order=0)]
        public ClienteWS.ServiceClienteWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ClienteWS.ServiceClienteWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://ws/", Order=0)]
        public ClienteWS.ServiceClienteWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ClienteWS.ServiceClienteWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPago", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ProcesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int total_pagar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int total_pago;
        
        public ProcesarPagoRequest() {
        }
        
        public ProcesarPagoRequest(int total_pagar, int total_pago) {
            this.total_pagar = total_pagar;
            this.total_pago = total_pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPagoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ProcesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public ProcesarPagoResponse() {
        }
        
        public ProcesarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Loggin", Namespace="http://ws/", Order=0)]
        public ClienteWS.ServiceClienteWS.LogginRequestBody Body;
        
        public LogginRequest() {
        }
        
        public LogginRequest(ClienteWS.ServiceClienteWS.LogginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LogginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public LogginRequestBody() {
        }
        
        public LogginRequestBody(string user, string contrasena) {
            this.user = user;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogginResponse", Namespace="http://ws/", Order=0)]
        public ClienteWS.ServiceClienteWS.LogginResponseBody Body;
        
        public LogginResponse() {
        }
        
        public LogginResponse(ClienteWS.ServiceClienteWS.LogginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LogginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public LogginResponseBody() {
        }
        
        public LogginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsoperacionesChannel : ClienteWS.ServiceClienteWS.wsoperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsoperacionesClient : System.ServiceModel.ClientBase<ClienteWS.ServiceClienteWS.wsoperaciones>, ClienteWS.ServiceClienteWS.wsoperaciones {
        
        public wsoperacionesClient() {
        }
        
        public wsoperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsoperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsoperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsoperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.ServiceClienteWS.helloResponse ClienteWS.ServiceClienteWS.wsoperaciones.hello(ClienteWS.ServiceClienteWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ClienteWS.ServiceClienteWS.helloRequest inValue = new ClienteWS.ServiceClienteWS.helloRequest();
            inValue.Body = new ClienteWS.ServiceClienteWS.helloRequestBody();
            inValue.Body.name = name;
            ClienteWS.ServiceClienteWS.helloResponse retVal = ((ClienteWS.ServiceClienteWS.wsoperaciones)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.helloResponse> ClienteWS.ServiceClienteWS.wsoperaciones.helloAsync(ClienteWS.ServiceClienteWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.helloResponse> helloAsync(string name) {
            ClienteWS.ServiceClienteWS.helloRequest inValue = new ClienteWS.ServiceClienteWS.helloRequest();
            inValue.Body = new ClienteWS.ServiceClienteWS.helloRequestBody();
            inValue.Body.name = name;
            return ((ClienteWS.ServiceClienteWS.wsoperaciones)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.ServiceClienteWS.ProcesarPagoResponse ClienteWS.ServiceClienteWS.wsoperaciones.ProcesarPago(ClienteWS.ServiceClienteWS.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPago(request);
        }
        
        public int ProcesarPago(int total_pagar, int total_pago) {
            ClienteWS.ServiceClienteWS.ProcesarPagoRequest inValue = new ClienteWS.ServiceClienteWS.ProcesarPagoRequest();
            inValue.total_pagar = total_pagar;
            inValue.total_pago = total_pago;
            ClienteWS.ServiceClienteWS.ProcesarPagoResponse retVal = ((ClienteWS.ServiceClienteWS.wsoperaciones)(this)).ProcesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.ProcesarPagoResponse> ClienteWS.ServiceClienteWS.wsoperaciones.ProcesarPagoAsync(ClienteWS.ServiceClienteWS.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.ProcesarPagoResponse> ProcesarPagoAsync(int total_pagar, int total_pago) {
            ClienteWS.ServiceClienteWS.ProcesarPagoRequest inValue = new ClienteWS.ServiceClienteWS.ProcesarPagoRequest();
            inValue.total_pagar = total_pagar;
            inValue.total_pago = total_pago;
            return ((ClienteWS.ServiceClienteWS.wsoperaciones)(this)).ProcesarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWS.ServiceClienteWS.LogginResponse ClienteWS.ServiceClienteWS.wsoperaciones.Loggin(ClienteWS.ServiceClienteWS.LogginRequest request) {
            return base.Channel.Loggin(request);
        }
        
        public bool Loggin(string user, string contrasena) {
            ClienteWS.ServiceClienteWS.LogginRequest inValue = new ClienteWS.ServiceClienteWS.LogginRequest();
            inValue.Body = new ClienteWS.ServiceClienteWS.LogginRequestBody();
            inValue.Body.user = user;
            inValue.Body.contrasena = contrasena;
            ClienteWS.ServiceClienteWS.LogginResponse retVal = ((ClienteWS.ServiceClienteWS.wsoperaciones)(this)).Loggin(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.LogginResponse> ClienteWS.ServiceClienteWS.wsoperaciones.LogginAsync(ClienteWS.ServiceClienteWS.LogginRequest request) {
            return base.Channel.LogginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.ServiceClienteWS.LogginResponse> LogginAsync(string user, string contrasena) {
            ClienteWS.ServiceClienteWS.LogginRequest inValue = new ClienteWS.ServiceClienteWS.LogginRequest();
            inValue.Body = new ClienteWS.ServiceClienteWS.LogginRequestBody();
            inValue.Body.user = user;
            inValue.Body.contrasena = contrasena;
            return ((ClienteWS.ServiceClienteWS.wsoperaciones)(this)).LogginAsync(inValue);
        }
    }
}
